/*
 * CANDIDATE: I_Product is listed as the released direction for CC-01 / MARA.
 * Before activating: confirm I_Product is released on the target product/release,
 * confirm element names 'Material' and 'MaterialType' exist on I_Product,
 * confirm the view is licensed and accessible.
 *
 * Verification status: Needs target verification
 * Generated by: zcc_legacy_materials_agent
 */

@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Material by Type — modernized from ZCC_LEGACY_MATERIALS'
@Metadata.ignorePropagatedAnnotations: true

define view entity I_MaterialByType
  as select from I_Product /* candidate: confirm I_Product is released on target */
{
      /*
       * candidate: confirm element name 'Material' exists on I_Product
       *            and maps to MARA-MATNR on the target release
       */
  key Material,        /* candidate */

      /*
       * candidate: confirm element name 'MaterialType' exists on I_Product
       *            and maps to MARA-MTART on the target release
       */
      MaterialType     /* candidate */
}
