"! ABAP Unit tests for ZCL_LEGACY_MATERIALS
"! Verification status: Needs target verification
"! Generated by: zcc_legacy_materials_agent
CLASS zcl_legacy_materials_test DEFINITION
  FINAL
  FOR TESTING
  RISK LEVEL HARMLESS
  DURATION SHORT.

  PRIVATE SECTION.

    DATA cut TYPE REF TO zcl_legacy_materials.  " class under test

    METHODS setup.

    "! Helper: build a ty_materials table from inline data.
    METHODS make_items
      IMPORTING
        it_raw           TYPE STANDARD TABLE
      RETURNING
        VALUE(rt_items)  TYPE zcl_legacy_materials=>ty_materials.

    "! Test (F-04 modernized — empty-result guard):
    "! When the input is empty, test_friend_apply_empty_guard returns an empty table
    "! and does NOT crash or modify anything.
    METHODS empty_result_returns_empty_table FOR TESTING.

    "! Test (pass-through):
    "! A pre-built table with two materials passes through
    "! test_friend_apply_empty_guard without modification.
    METHODS non_empty_result_passes_through  FOR TESTING.

    "! Test (field preservation):
    "! A material with MaterialType = 'ROH' passes through and the
    "! MaterialType field is preserved exactly.
    METHODS material_type_preserved          FOR TESTING.

    "! Test (F-05 stub — display_stub_returns_4):
    "! Calling display_stub with any input sets ev_subrc = 4.
    METHODS display_stub_returns_4           FOR TESTING.

ENDCLASS.


CLASS zcl_legacy_materials_test IMPLEMENTATION.

  METHOD setup.
    cut = NEW zcl_legacy_materials( ).
  ENDMETHOD.

  METHOD make_items.
    "  The caller passes a table of the same structure; we just assign it.
    "  Using CORRESPONDING so the helper works with inline VALUE expressions.
    rt_items = CORRESPONDING #( it_raw ).
  ENDMETHOD.

  " -------------------------------------------------------------------------
  METHOD empty_result_returns_empty_table.
    DATA(lt_empty) = VALUE zcl_legacy_materials=>ty_materials( ).

    DATA(lt_result) = cut->test_friend_apply_empty_guard( lt_empty ).

    cl_abap_unit_assert=>assert_equals(
      act = lines( lt_result )
      exp = 0
      msg = 'Empty input must produce empty output (empty-result guard, F-04)' ).
  ENDMETHOD.

  " -------------------------------------------------------------------------
  METHOD non_empty_result_passes_through.
    DATA(lt_input) = VALUE zcl_legacy_materials=>ty_materials(
      ( Material = 'MAT-001' MaterialType = 'FERT' )
      ( Material = 'MAT-002' MaterialType = 'ROH'  ) ).

    DATA(lt_result) = cut->test_friend_apply_empty_guard( lt_input ).

    cl_abap_unit_assert=>assert_equals(
      act = lines( lt_result )
      exp = 2
      msg = 'Two-row input must pass through unchanged' ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-Material
      exp = 'MAT-001'
      msg = 'First material number must be preserved' ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 2 ]-Material
      exp = 'MAT-002'
      msg = 'Second material number must be preserved' ).
  ENDMETHOD.

  " -------------------------------------------------------------------------
  METHOD material_type_preserved.
    DATA(lt_input) = VALUE zcl_legacy_materials=>ty_materials(
      ( Material = 'RAW-001' MaterialType = 'ROH' ) ).

    DATA(lt_result) = cut->test_friend_apply_empty_guard( lt_input ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-MaterialType
      exp = 'ROH'
      msg = 'MaterialType ROH must be preserved exactly through the guard' ).
  ENDMETHOD.

  " -------------------------------------------------------------------------
  METHOD display_stub_returns_4.
    DATA(lt_any) = VALUE zcl_legacy_materials=>ty_materials(
      ( Material = 'ANY-001' MaterialType = 'HAWA' ) ).

    DATA lv_subrc TYPE sysubrc.
    cut->display_stub(
      EXPORTING it_materials = lt_any
      IMPORTING ev_subrc     = lv_subrc ).

    cl_abap_unit_assert=>assert_equals(
      act = lv_subrc
      exp = 4
      msg = 'display_stub must return ev_subrc = 4 (not yet implemented, F-05)' ).
  ENDMETHOD.

ENDCLASS.
