"! <p class="shorttext synchronized">Modernized from ZCC_LEGACY_MATERIALS</p>
"! Verification status: Needs target verification
"! Generated by: zcc_legacy_materials_agent
"!
"! Replaces the legacy REPORT zcc_legacy_materials.
"! Key changes:
"!   F-01 CC-10 : TABLES statement removed.
"!   F-02       : SELECT-OPTIONS removed; caller passes RANGE OF matnr instead.
"!   F-03 CC-01 : Direct SELECT on MARA replaced by CDS view I_MaterialByType
"!                (candidate — verify release, element names, licensing).
"!   F-04 CC-09 : WRITE 'No materials found' removed; empty table returned to caller.
"!   F-05 CC-08 : REUSE_ALV_GRID_DISPLAY replaced by display_stub (see method).
"!   F-06 CC-09 : WRITE 'Display failed' removed; stub sets ev_subrc = 4.
CLASS zcl_legacy_materials DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FRIENDS zcl_legacy_materials_test.

  PUBLIC SECTION.

    "! Structure matching I_MaterialByType CDS view exactly.
    "! CamelCase field names MUST match the CDS element names so that
    "! SELECT … INTO CORRESPONDING FIELDS resolves without AS aliases.
    TYPES:
      BEGIN OF ty_material,
        Material     TYPE matnr,  /* candidate: verify correct ABAP type for I_Product-Material     */
        MaterialType TYPE mtart,  /* candidate: verify correct ABAP type for I_Product-MaterialType */
      END OF ty_material,
      ty_materials TYPE STANDARD TABLE OF ty_material WITH EMPTY KEY.

    "! Read materials from I_MaterialByType CDS view.
    "! Empty-result guard (legacy F-04): if no rows are found, an empty table
    "! is returned — the caller decides what to do; no screen output is produced.
    "! @parameter it_material_range | Material-number filter (RANGE OF matnr).
    "! @parameter rt_materials       | Result table; may be empty.
    METHODS run
      IMPORTING it_material_range TYPE RANGE OF matnr
      RETURNING VALUE(rt_materials) TYPE ty_materials.

    "! Output stub — replaces REUSE_ALV_GRID_DISPLAY (F-05) and both
    "! WRITE statements (F-04, F-06).
    "!
    "! TODO: Replace with a RAP-based query exposed as a Fiori Elements
    "!       List Report OData V4 service.  No direct code equivalent —
    "!       the output channel must change.
    "!
    "! @parameter it_materials | Materials to display (ignored until implemented).
    "! @parameter ev_subrc     | 4 = not yet implemented; 0 = success (future).
    METHODS display_stub
      IMPORTING it_materials TYPE ty_materials
      EXPORTING ev_subrc     TYPE sysubrc.

    "! Test-friend: apply the empty-result guard logic in isolation (no DB call).
    "! Returns the input table unchanged; used by unit tests to verify the guard
    "! does not crash or mutate data.
    METHODS test_friend_apply_empty_guard
      IMPORTING it_input         TYPE ty_materials
      RETURNING VALUE(rt_out)    TYPE ty_materials.

  PRIVATE SECTION.

    "! Select materials from the I_MaterialByType CDS view.
    "! candidate: I_MaterialByType is built on I_Product — verify release on target.
    METHODS select_materials
      IMPORTING it_material_range  TYPE RANGE OF matnr
      RETURNING VALUE(rt_mats)     TYPE ty_materials.

ENDCLASS.


CLASS zcl_legacy_materials IMPLEMENTATION.

  METHOD run.
    rt_materials = select_materials( it_material_range ).
    "  Empty-result guard (F-04 modernized):
    "  Legacy code wrote 'No materials found' and returned.
    "  Here we simply return the empty table — the caller decides the reaction.
  ENDMETHOD.

  METHOD display_stub.
    "  -----------------------------------------------------------------------
    "  STUB — NOT YET IMPLEMENTED (replaces F-05 and F-04/F-06 WRITE calls)
    "  -----------------------------------------------------------------------
    "  TODO: Replace with a RAP-based query exposed as a Fiori Elements
    "        List Report OData V4 service.  No direct code equivalent —
    "        the output channel must change.
    "  -----------------------------------------------------------------------
    ev_subrc = 4.
    "  Suppress unused-parameter warning:
    ASSERT it_materials IS SUPPLIED.
  ENDMETHOD.

  METHOD test_friend_apply_empty_guard.
    rt_out = it_input.
  ENDMETHOD.

  METHOD select_materials.
    "  candidate: I_MaterialByType is built on I_Product /* candidate */
    "  Verify I_Product is released on the target product/release before activating.
    SELECT Material,      /* candidate */
           MaterialType   /* candidate */
      FROM I_MaterialByType /* candidate */
      WHERE Material IN @it_material_range
      INTO CORRESPONDING FIELDS OF TABLE @rt_mats.
  ENDMETHOD.

ENDCLASS.
