/*
 * CDS View Entity : I_OpenSalesOrder
 * Generated by   : zsd_open_orders_agent
 * Source program : ZSD_OPEN_ORDERS
 * Verification status: Needs target verification
 *
 * Candidate notes
 * ---------------
 * - I_SalesDocument       /* candidate */ — release contract not confirmed
 * - I_SalesDocumentItem   /* candidate */ — release contract not confirmed
 * - I_Customer            /* candidate */ — release contract not confirmed
 * - DeliveryStatus field  /* candidate */ — no confirmed released CDS view
 *     covering VBUP-LFSTA; see association stub _DeliveryStatus below.
 * - CustomerName field    /* candidate */ — field name in I_Customer not confirmed
 *
 * Human decision required before activation:
 *   See README.md § "What a human must still decide"
 */

@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #CHECK
@EndUserText.label: 'Open Sales Orders per Customer'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType: {
    serviceQuality: #X,
    sizeCategory:   #M,
    dataClass:      #TRANSACTIONAL
}

define view entity I_OpenSalesOrder
  as select from I_SalesDocument /* candidate */ as SalesDoc

  join I_SalesDocumentItem /* candidate */ as SalesDocItem
    on SalesDocItem.SalesDocument = SalesDoc.SalesDocument

  /*
   * DELIVERY-STATUS STUB
   * --------------------
   * The legacy code reads VBUP-LFSTA to identify open items
   * (CHECK ls_vbup-lfsta <> 'C').  No confirmed released CDS view
   * covering VBUP exists at the time of writing.
   *
   * TODO (human): identify the correct released view/association for
   *   VBUP-LFSTA and replace this comment + the WHERE clause candidate
   *   below with the verified join.
   *
   * Placeholder association kept as comment to document intent:
   *   association [0..1] to I_SalesDocumentItemDeliveryStatus /* candidate */
   *     as _DeliveryStatus
   *     on  _DeliveryStatus.SalesDocument     = SalesDoc.SalesDocument
   *     and _DeliveryStatus.SalesDocumentItem = SalesDocItem.SalesDocumentItem
   */

  left outer join I_Customer /* candidate */ as Customer
    on Customer.Customer = SalesDoc.SoldToParty /* candidate */

{
  key SalesDoc.SalesDocument             as SalesDocument,
      SalesDoc.CreationDate              as CreationDate,
      SalesDoc.SoldToParty               as SoldToParty,        /* candidate */
      Customer.CustomerName              as CustomerName,        /* candidate */
  key SalesDocItem.SalesDocumentItem     as SalesDocumentItem,  /* candidate */
      SalesDocItem.Material              as Material,            /* candidate */
      SalesDocItem.OrderQuantity         as OrderQuantity,       /* candidate */
      SalesDocItem.NetAmount             as NetAmount            /* candidate */
}

where
  /*
   * Open-item filter: exclude fully delivered items.
   * Legacy: CHECK ls_vbup-lfsta <> 'C'
   *
   * TODO (human): once the delivery-status join (see stub above) is
   *   resolved, replace the field reference below with the verified path,
   *   e.g. _DeliveryStatus.DeliveryStatus <> 'C'.
   *
   * Also decide whether partially delivered ('B') should be included —
   * see README.md § "What a human must still decide", item 5.
   */
      SalesDocItem.DeliveryStatus <> 'C' /* candidate */

  /*
   * Sales organisation filter is applied in the ABAP consumer
   * (zcl_open_orders) via a WHERE clause on SalesOrganization,
   * keeping this CDS view reusable.
   *
   * TODO (human): verify that I_SalesDocument exposes SalesOrganization
   *   with that exact field name.
   */
