"! <p class="shorttext synchronized">Open Sales Orders per Customer</p>
"! Modernized from legacy report ZSD_OPEN_ORDERS.
"! Generated by : zsd_open_orders_agent
"! Verification status: Needs target verification
"!
"! All accesses go through the CDS view I_OpenSalesOrder.
"! Fields marked /* candidate */ have not been verified on the target system.
"! GUI/output interactions are replaced by clearly marked stubs.
CLASS zcl_open_orders DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FRIENDS zcl_open_orders_test.

  PUBLIC SECTION.

    "! Aggregated order row.  CamelCase field names match the CDS element
    "! names exactly so that SELECT … INTO CORRESPONDING FIELDS resolves
    "! without AS aliases.
    TYPES:
      BEGIN OF ty_order,
        SalesDocument     TYPE vbeln_va,   "< CDS: SalesDocument
        CreationDate      TYPE erdat,      "< CDS: CreationDate
        SoldToParty       TYPE kunnr,      "< CDS: SoldToParty     /* candidate */
        CustomerName      TYPE name1_gp,   "< CDS: CustomerName    /* candidate */
        SalesDocumentItem TYPE posnr_va,   "< CDS: SalesDocumentItem /* candidate */
        Material          TYPE matnr,      "< CDS: Material         /* candidate */
        OrderQuantity     TYPE kwmeng,     "< CDS: OrderQuantity    /* candidate */
        NetAmount         TYPE netwr_ap,   "< CDS: NetAmount        /* candidate */
        TotalNetAmount    TYPE netwr_ap,   "< computed — not CDS-sourced; SUM of
                                           "  NetAmount over all returned rows
      END OF ty_order.

    TYPES ty_orders TYPE STANDARD TABLE OF ty_order WITH EMPTY KEY.

    "! Entry point.  Reads open sales orders from I_OpenSalesOrder,
    "! aggregates TotalNetAmount, sorts and returns the result table.
    "!
    "! @parameter iv_sales_org   | Sales organisation (mandatory in legacy: p_vkorg)
    "! @parameter it_sold_to     | Customer range (legacy: s_kunnr)
    "! @parameter it_creat_date  | Creation-date range (legacy: s_erdat)
    "! @parameter rt_orders      | Sorted, aggregated open orders
    METHODS run
      IMPORTING
        iv_sales_org   TYPE vkorg
        it_sold_to     TYPE RANGE OF kunnr
        it_creat_date  TYPE RANGE OF erdat
      RETURNING
        VALUE(rt_orders) TYPE ty_orders.

    "! Output stub — replaces WRITE / ULINE list output (findings F-15, F-16).
    "!
    "! TODO (human): replace this stub with a RAP query exposed through a
    "!   Fiori Elements List Report OData V4 endpoint, or with an ABAP
    "!   Application Job output channel as appropriate for the target
    "!   deployment.  See README.md § "What a human must still decide", item 6.
    "!
    "! @parameter it_orders | Table to display
    "! @parameter ev_subrc  | 0 = success (stub always sets 0)
    METHODS display_stub
      IMPORTING
        it_orders      TYPE ty_orders
      EXPORTING
        ev_subrc       TYPE sysubrc.

  PRIVATE SECTION.

    "! Executes ABAP SQL against I_OpenSalesOrder.
    "! Access-control check is delegated to @AccessControl.authorizationCheck: #CHECK
    "! on the CDS view itself.
    METHODS select_open_orders
      IMPORTING
        iv_sales_org   TYPE vkorg
        it_sold_to     TYPE RANGE OF kunnr
        it_creat_date  TYPE RANGE OF erdat
      RETURNING
        VALUE(rt_items) TYPE ty_orders.

    "! Pure business-logic method: sorts the table and computes TotalNetAmount.
    "! Exposed as a friend method so zcl_open_orders_test can call it directly
    "! with a synthetic table, bypassing the database.
    "!
    "! @parameter it_raw     | Rows as returned by select_open_orders
    "! @parameter rt_orders  | Sorted rows with TotalNetAmount populated
    METHODS apply_sort_and_aggregate
      IMPORTING
        it_raw           TYPE ty_orders
      RETURNING
        VALUE(rt_orders) TYPE ty_orders.

ENDCLASS.


CLASS zcl_open_orders IMPLEMENTATION.

  METHOD run.
    DATA(lt_raw) = select_open_orders(
                     iv_sales_org  = iv_sales_org
                     it_sold_to    = it_sold_to
                     it_creat_date = it_creat_date ).
    rt_orders = apply_sort_and_aggregate( lt_raw ).
  ENDMETHOD.


  METHOD select_open_orders.
    "--------------------------------------------------------------------
    "  Read open sales orders from the CDS view.
    "
    "  Findings addressed here:
    "   F-06  CC-01 — replaced SELECT on VBAK  with I_SalesDocument    /* candidate */
    "   F-07  CC-12 — eliminated nested SELECT…ENDSELECT loops
    "   F-08  CC-01 — replaced SELECT on VBAP  with I_SalesDocumentItem /* candidate */
    "   F-09  CC-01 — delivery-status filter moved to CDS WHERE clause
    "   F-10  CC-01 — replaced SELECT on KNA1  with I_Customer join     /* candidate */
    "   F-11  CC-10 — MOVE-CORRESPONDING replaced by CORRESPONDING #( )
    "                 (implicit via SELECT … INTO CORRESPONDING FIELDS)
    "   F-18       — LFSTA 'C' filter preserved as DeliveryStatus <> 'C' /* candidate */
    "                in CDS view WHERE clause
    "
    "  NOTE: SalesOrganization field name in I_SalesDocument not confirmed. /* candidate */
    "--------------------------------------------------------------------
    SELECT
        SalesDocument,      "< I_SalesDocument     /* candidate */
        CreationDate,
        SoldToParty,        "< I_SalesDocument     /* candidate */
        CustomerName,       "< I_Customer join      /* candidate */
        SalesDocumentItem,  "< I_SalesDocumentItem  /* candidate */
        Material,           "< I_SalesDocumentItem  /* candidate */
        OrderQuantity,      "< I_SalesDocumentItem  /* candidate */
        NetAmount           "< I_SalesDocumentItem  /* candidate */
      FROM I_OpenSalesOrder /* candidate */
      WHERE SalesOrganization = @iv_sales_org  /* candidate — field name unverified */
        AND SoldToParty       IN @it_sold_to   /* candidate */
        AND CreationDate      IN @it_creat_date
      INTO CORRESPONDING FIELDS OF TABLE @rt_items.
    "  DeliveryStatus <> 'C' is enforced by the CDS view WHERE clause (F-09, F-18).
  ENDMETHOD.


  METHOD apply_sort_and_aggregate.
    "--------------------------------------------------------------------
    "  Business logic preserved from legacy FORM print_list / FORM get_data:
    "
    "   F-11  CC-10 — arithmetic ADD … TO replaced by modern loop aggregate
    "   F-17  CC-10 — ADD … TO (line 63) obsolete; replaced below
    "   F-12  CC-11 — FORM get_data      — replaced by private method
    "   F-13  CC-11 — FORM print_list    — replaced by private method
    "   F-14  CC-11 — PERFORM calls      — replaced by method calls
    "   F-16  CC-09 — AT NEW / ENDAT     — replaced by sort + loop
    "--------------------------------------------------------------------

    rt_orders = it_raw.

    " Legacy: SORT it_orders BY kunnr vbeln posnr
    SORT rt_orders BY SoldToParty ASCENDING
                      SalesDocument ASCENDING
                      SalesDocumentItem ASCENDING.

    " Legacy: ADD it_orders-netwr TO w_total  (accumulated across all rows)
    " Modernised: compute the scalar total and stamp it on every row so that
    " any downstream consumer (Fiori tile KPI, Application Job log, etc.) can
    " display it without a separate aggregation call.
    DATA(lv_total) = REDUCE netwr_ap(
                       INIT s TYPE netwr_ap
                       FOR  row IN rt_orders
                       NEXT s = s + row-NetAmount ).

    LOOP AT rt_orders ASSIGNING FIELD-SYMBOL(<row>).
      <row>-TotalNetAmount = lv_total.
    ENDLOOP.
  ENDMETHOD.


  METHOD display_stub.
    "--------------------------------------------------------------------
    "  STUB — replaces WRITE / ULINE list output (findings F-15, F-16).
    "
    "  The legacy FORM print_list used:
    "    SKIP / WRITE … COLOR COL_HEADING / ULINE / AT NEW … ENDAT
    "  None of these constructs are permitted in ABAP Cloud.
    "
    "  TODO (human): implement one of the following:
    "    a) Expose results through a RAP-based OData V4 service bound to a
    "       Fiori Elements List Report application.
    "    b) Write output to an ABAP Application Job log using the
    "       CL_APPL_LOG* / CL_BALI_LOG API.
    "    c) Return the table to the caller (e.g., an OData action) and let
    "       the UI layer render it.
    "  See README.md § "What a human must still decide", item 6.
    "--------------------------------------------------------------------
    ev_subrc = 0.  " stub always succeeds
    " it_orders intentionally not used until the stub is replaced.
    ASSERT 1 = 1.  " placeholder — suppress "unused parameter" warning
  ENDMETHOD.

ENDCLASS.
