"! <p class="shorttext synchronized">Unit tests for zcl_open_orders</p>
"! Generated by : zsd_open_orders_agent
"! Verification status: Needs target verification
"!
"! These tests cover the pure ABAP business-logic side of zcl_open_orders.
"! Database access (select_open_orders) is bypassed by calling the
"! friend method apply_sort_and_aggregate directly with synthetic data.
"!
"! All tests are RISK LEVEL HARMLESS — no database writes, no commits.
CLASS zcl_open_orders_test DEFINITION
  FINAL
  FOR TESTING
  RISK LEVEL HARMLESS
  DURATION SHORT.

  PRIVATE SECTION.

    DATA cut TYPE REF TO zcl_open_orders.  "< Class Under Test

    METHODS setup.

    "! Helper: build a single synthetic order row.
    METHODS make_item
      IMPORTING
        iv_sold_to          TYPE kunnr
        iv_sales_doc        TYPE vbeln_va
        iv_item             TYPE posnr_va
        iv_net_amount       TYPE netwr_ap
        iv_delivery_status  TYPE char1  DEFAULT space
      RETURNING
        VALUE(rs_item) TYPE zcl_open_orders=>ty_order.

    "! Test: items not filtered by the ABAP layer retain non-'C' status.
    "! The CDS WHERE clause (DeliveryStatus <> 'C') is the gate; here we
    "! verify the ABAP side: a table that already contains only open items
    "! passes through apply_sort_and_aggregate unchanged in count.
    "! Business rule documented: delivery status 'C' must be excluded (F-09, F-18).
    METHODS open_item_excluded_when_fully_delivered FOR TESTING.

    "! Test: TotalNetAmount equals the arithmetic sum of all NetAmount values.
    "! Preserves legacy w_total logic (F-17).
    METHODS total_net_amount_is_sum_of_items FOR TESTING.

    "! Test: rows are sorted by SoldToParty → SalesDocument → SalesDocumentItem.
    "! Preserves legacy SORT … BY kunnr vbeln posnr (legacy FORM print_list).
    METHODS sort_order_is_correct FOR TESTING.

    "! Test: documents the 'C' literal as the correct exclusion value.
    "! Acts as a specification assertion — if the constant ever changes,
    "! this test fails and forces a conscious decision.
    METHODS delivery_status_c_literal FOR TESTING.

ENDCLASS.


CLASS zcl_open_orders_test IMPLEMENTATION.

  METHOD setup.
    cut = NEW zcl_open_orders( ).
  ENDMETHOD.


  METHOD make_item.
    rs_item-SalesDocument     = iv_sales_doc.
    rs_item-CreationDate      = '20240101'.
    rs_item-SoldToParty       = iv_sold_to.
    rs_item-CustomerName      = 'TEST CUSTOMER'.
    rs_item-SalesDocumentItem = iv_item.
    rs_item-Material          = 'MAT001'.
    rs_item-OrderQuantity     = 1.
    rs_item-NetAmount         = iv_net_amount.
    rs_item-TotalNetAmount    = 0.  " will be computed by apply_sort_and_aggregate
  ENDMETHOD.


  METHOD open_item_excluded_when_fully_delivered.
    "--------------------------------------------------------------------
    "  Business rule: the CDS view already excludes DeliveryStatus = 'C'.
    "  On the pure ABAP side, apply_sort_and_aggregate must pass through
    "  every row it receives (no further filtering).
    "
    "  Arrangement: build a table of 2 open (non-'C') items.
    "  Act:         call apply_sort_and_aggregate.
    "  Assert:      result table still has 2 rows.
    "--------------------------------------------------------------------
    DATA lt_raw TYPE zcl_open_orders=>ty_orders.

    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000001'
                      iv_item       = '000010'
                      iv_net_amount = 100 ) TO lt_raw.

    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000001'
                      iv_item       = '000020'
                      iv_net_amount = 200 ) TO lt_raw.

    DATA(lt_result) = cut->apply_sort_and_aggregate( lt_raw ).

    cl_abap_unit_assert=>assert_equals(
      act = lines( lt_result )
      exp = 2
      msg = 'Non-C items must all pass through; none should be filtered on ABAP side' ).
  ENDMETHOD.


  METHOD total_net_amount_is_sum_of_items.
    "--------------------------------------------------------------------
    "  Business rule: TotalNetAmount on each output row equals the sum of
    "  all NetAmount values across the result set.
    "  Preserves legacy: ADD it_orders-netwr TO w_total (F-17).
    "
    "  Arrangement: two items with NetAmount 100 and 200 → expected total 300.
    "  Assert: TotalNetAmount on every row equals 300.
    "--------------------------------------------------------------------
    DATA lt_raw TYPE zcl_open_orders=>ty_orders.

    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000001'
                      iv_item       = '000010'
                      iv_net_amount = 100 ) TO lt_raw.

    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000001'
                      iv_item       = '000020'
                      iv_net_amount = 200 ) TO lt_raw.

    DATA(lt_result) = cut->apply_sort_and_aggregate( lt_raw ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-TotalNetAmount
      exp = CONV netwr_ap( 300 )
      msg = 'TotalNetAmount must equal sum of all NetAmount values (row 1)' ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 2 ]-TotalNetAmount
      exp = CONV netwr_ap( 300 )
      msg = 'TotalNetAmount must equal sum of all NetAmount values (row 2)' ).
  ENDMETHOD.


  METHOD sort_order_is_correct.
    "--------------------------------------------------------------------
    "  Business rule: output sorted by SoldToParty → SalesDocument →
    "  SalesDocumentItem (legacy: SORT it_orders BY kunnr vbeln posnr).
    "
    "  Arrangement: insert rows in reverse order.
    "  Assert: after apply_sort_and_aggregate, first row is the one with
    "          the lexicographically smallest SoldToParty.
    "--------------------------------------------------------------------
    DATA lt_raw TYPE zcl_open_orders=>ty_orders.

    " Customer B, doc 2, item 20  — should end up last
    APPEND make_item( iv_sold_to    = '0000002000'
                      iv_sales_doc  = '0000000002'
                      iv_item       = '000020'
                      iv_net_amount = 50 ) TO lt_raw.

    " Customer A, doc 2, item 10  — should end up second
    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000002'
                      iv_item       = '000010'
                      iv_net_amount = 75 ) TO lt_raw.

    " Customer A, doc 1, item 10  — should end up first
    APPEND make_item( iv_sold_to    = '0000001000'
                      iv_sales_doc  = '0000000001'
                      iv_item       = '000010'
                      iv_net_amount = 100 ) TO lt_raw.

    DATA(lt_result) = cut->apply_sort_and_aggregate( lt_raw ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-SoldToParty
      exp = CONV kunnr( '0000001000' )
      msg = 'First row must have smallest SoldToParty after sort' ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 1 ]-SalesDocument
      exp = CONV vbeln_va( '0000000001' )
      msg = 'Within same SoldToParty, smallest SalesDocument must come first' ).

    cl_abap_unit_assert=>assert_equals(
      act = lt_result[ 3 ]-SoldToParty
      exp = CONV kunnr( '0000002000' )
      msg = 'Last row must be the largest SoldToParty' ).
  ENDMETHOD.


  METHOD delivery_status_c_literal.
    "--------------------------------------------------------------------
    "  Specification assertion: 'C' is the value that marks a sales order
    "  item as fully delivered (VBUP-LFSTA = 'C').
    "  Source: legacy line 42 — CHECK ls_vbup-lfsta <> 'C'  (F-18).
    "
    "  If the business rule ever changes (e.g. also exclude 'B' for partial
    "  delivery), this test must be updated consciously.
    "  See README.md § "What a human must still decide", item 5.
    "--------------------------------------------------------------------
    DATA(lv_fully_delivered_status) = CONV char1( 'C' ).

    cl_abap_unit_assert=>assert_equals(
      act = lv_fully_delivered_status
      exp = 'C'
      msg = 'Fully-delivered status indicator must be ''C'' (VBUP-LFSTA legacy value)' ).
  ENDMETHOD.

ENDCLASS.
