// Presentation and separately labelled assessment; never modifies Bob's raw JSON.
let recordedAudits=[];
const assessmentLabel='Scored by Claude - confirmed by Sena, 26 Sep';
function recordedForCurrent(){return recordedAudits.find(x=>x.raw===rawText);}
const findingHeadlines={"ZFI_VENDOR_AGING": ["Reads accounting tables whose cloud availability needs checking.", "Reads supplier data directly from an SAP table.", "Uses native SQL, which ABAP Cloud does not allow.", "Uses an old-style table with an implicit header row.", "Writes a file to the application server instead of a cloud integration.", "Starts another classic report with SUBMIT.", "Claims to convert currency, but only updates a log.", "Bob flags the report structure correctly, but uses the wrong rule."], "ZSD_OPEN_ORDERS": ["Declares a work area tied to classic SAP GUI screens.", "Uses an old-style table with an implicit header row.", "Bob questions a type reference to a database field.", "Bob questions another type reference to a database field.", "Uses a classic selection screen and a database-field type.", "Reads sales headers directly from an SAP table.", "Runs database queries inside nested loops.", "Reads sales items directly from an SAP table.", "Reads delivery status directly from an SAP table.", "Reads customer data directly from an SAP table.", "Bob questions MOVE-CORRESPONDING; the assessment disagrees.", "Uses a classic subroutine instead of a method.", "Uses another classic subroutine instead of a method.", "Calls the classic subroutines flagged above.", "Prints a classic list that needs a cloud UI replacement.", "Uses a control break in the classic list output.", "Uses an older arithmetic statement.", "The delivery-status comment does not match its filter."], "ZMM_MASS_PRICE_UPDATE": ["Calls a GUI popup that is unavailable in ABAP Cloud.", "Reads material prices directly from an SAP table.", "Updates SAP prices directly, bypassing standard posting logic.", "Replays SAP GUI screens to change a material.", "Prints a classic list that needs a cloud UI replacement.", "Uses classic subroutines instead of methods.", "Bob questions declarations; the assessment disagrees.", "Changes standard prices without checking price control."], "ZCC_LEGACY_MATERIALS": ["Declares a work area tied to classic SAP GUI screens.", "Uses a selection screen that depends on SAP GUI.", "Reads material data directly from an SAP table.", "Prints a classic list that needs a cloud UI replacement.", "Displays a grid through a classic SAP GUI function.", "Prints another classic list line; this repeats an earlier issue."]};
function plainFinding(f){const a=recordedForCurrent();const n=Number(f.id.replace("F-",""))-1;return a&&findingHeadlines[report.program]?.[n]||f.title||f.reason.split(/\n|\. /)[0];}
// Plain-language layer: every label on screen should read like the pitch, not like a data field.
const programPlain={ZFI_VENDOR_AGING:'Lists unpaid supplier invoices by how overdue they are',ZSD_OPEN_ORDERS:'Prints open sales orders for each customer',ZMM_MASS_PRICE_UPDATE:'Raises the price of every material in a plant',ZCC_LEGACY_MATERIALS:'Shows a list of materials'};
const programTitles={ZFI_VENDOR_AGING:'Unpaid supplier invoices',ZSD_OPEN_ORDERS:'Open customer orders',ZMM_MASS_PRICE_UPDATE:'Material price updates',ZCC_LEGACY_MATERIALS:'Material list'};
const ruleName={'CC-01':'reads SAP tables directly','CC-02':'reads finance tables directly','CC-03':'writes straight into SAP tables','CC-04':'replays SAP screens','CC-05':'uses database-specific SQL','CC-06':'writes files on the server','CC-07':'starts other old reports','CC-08':'calls SAP functions not open to cloud code','CC-09':'prints an old-style screen list','CC-10':'uses outdated ABAP syntax','CC-11':'uses old subroutines','CC-12':'runs slow nested queries'};
const ruleLabel=r=>ruleName[r]?`Rule ${r}: ${ruleName[r]}`:'Outside the 12-rule list';
const problemNo=f=>/^F-\d+$/.test(f.id)?'Problem '+Number(f.id.slice(2)):f.id;
const linesText=f=>f.line_start===f.line_end?`code line ${f.line_start}`:`code lines ${f.line_start}–${f.line_end}`;
const adviceText={Rebuild:'rebuild it',Refactor:'clean it up',Retire:'retire it',Keep:'keep it'};
const triedText=p=>p==='ZFI_VENDOR_AGING'?'New version being tried on a free SAP trial system':'Not yet tried on a real SAP system';
Object.assign(statusText,{observed:'Bob saw this in the code',needs_verification:'Must be confirmed on a real SAP system',verified_on_target:'Reported as checked on SAP'});
document.querySelectorAll('#filter option').forEach(o=>{if(statusText[o.value])o.textContent=statusText[o.value];});
function verdictFor(f){
 const value=recordedForCurrent()?.assessment[f.id]||'';
 if(/^(Match|Bonus) /.test(value))return['✓ Bob was right','good','Yes. This problem is on our sealed answer list, and Bob found it on the right lines.'];
 if(value==='Correct extra')return['✓ Right, and not on our list','good','Yes. This is a real problem that our answer list did not include.'];
 if(value.startsWith('Duplicate '))return['✓ Right, but a repeat','repeat','Yes, but Bob already reported this same problem earlier, so it is counted once.'];
 if(value==='Correct observation - unscored')return['✓ Fair point, not counted','repeat','A fair point. Our answer list marks this as a decision for a person, so it is not counted either way.'];
 if(value==='Partially correct')return['◐ Partly right','partial','Partly. Bob found the right place but the reason or rule is not fully right.'];
 if(value==='Incorrect')return['✗ Bob was wrong','wrong','No. Our answer list does not treat this as a problem.'];
 return['Not judged','none','This finding has not been judged against an answer list.'];
}
function assessmentFor(f){return verdictFor(f)[0];}
function programButtons(){
 const button=([key,s])=>`<button class="program-card ${key===activeReportKey?'chosen':''}" data-program="${esc(key)}"><strong>${esc(s.report.program)}</strong><span class="program-plain">${esc(programPlain[s.report.program]||(s.isDesign?'Made-up design example':'A report you uploaded'))}</span><span>${s.report.findings.length} problems flagged by Bob</span></button>`;
 const entries=[...loadedReports];const main=entries.filter(([key])=>key.startsWith('recorded-'));
 const imports=entries.filter(([key,s])=>!key.startsWith('recorded-')&&!s.isDesign);
 return main.map(button).join('')+(imports.length?`<details class="your-imports" ${imports.some(([key])=>key===activeReportKey)?'open':''}><summary>Reports you uploaded (${imports.length})</summary><div class="program-strip">${imports.map(button).join('')}</div></details>`:'');
}
function bindPrograms(node){node.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>{const page=location.hash;switchReport(b.dataset.program);location.hash=page||'#overview';paintWorkspace();});}
function paintOverview(){
 const steps=[['1','We hid the problems','We wrote four old-style SAP programs and hid 41 known problems in them. The answer list was sealed on 24 Sep, before Bob saw any code.'],['2','Bob looked for them','Bob read each program and listed every problem it saw, with the line number and its reason.'],['3','We checked Bob’s list','Claude compared Bob’s list with the sealed answers. Sena confirmed every call on 26 Sep.']];
 const cards=[['Rule problems Bob caught','27 of 29','29 of the hidden problems break a written SAP cloud rule. Bob found 27 of them on the right lines.'],['Logic bugs Bob caught','1 of 12','12 hidden problems are business-logic mistakes that no rule list covers. Bob found 1, so a person still has to check the logic.'],['How often Bob was right','29 of 32','We could judge 32 of Bob’s findings, and 29 were correct (91%). Six repeats and two fair points our list did not count are left out.']];
 const spend=[['Reading the four programs','0.661'],['Rewriting one program as new cloud code','0.807'],['Fixing that rewrite after our review','1.030'],['Rewriting the other three programs at once','1.760']];
 const mascot=window.CLEAN_CORE_DEMO_CONFIG?.SHOW_MASCOT===true?'<img class="coin-art" src="assets/bob-coins.png" alt="" width="200" height="200">':'';
 const p=report.program,a=report.summary.draft_verdict_hint;
 $('overview-view').innerHTML=`<ol class="explain-steps">${steps.map(([n,t,d])=>`<li><span class="step-number">${n}</span><div><h3>${t}</h3><p>${d}</p></div></li>`).join('')}</ol>
 <div class="metric-grid">${cards.map(([t,v,n])=>`<article class="metric"><span>${t}</span><strong>${v}</strong><small>${n}</small></article>`).join('')}
 <article class="metric metric-coins">${mascot}<div class="coin-summary"><span class="eyebrow">Bob credits spent</span><div class="coin-value"><strong>≈4.3 of 40</strong><span>Bobcoin</span></div><p>Each hackathon team gets 40 Bobcoin to pay for Bob’s work. This whole project used about a tenth of it.</p><div class="coin-budget"><div class="coin-track" role="meter" aria-label="Bobcoin used" aria-valuemin="0" aria-valuemax="40" aria-valuenow="4.258"><span style="width:10.645%"></span></div><div class="coin-budget-labels"><span>4.258 used</span><span>35.742 left</span></div></div><ul class="coin-breakdown">${spend.map(([t,v])=>`<li><span>${t}</span><b>${v}</b></li>`).join('')}</ul></div></article></div>
 <details class="study-method"><summary>Where these numbers come from</summary><p>The 41 problems sit in made-up programs we wrote for this test, so the numbers describe this test only, not Bob on every SAP system. Scoring notes are in docs/scoring/. Bobcoin figures come from Bob’s own task summaries.</p></details>
 <h2 class="plain-heading">Pick a program to see what Bob found</h2><div class="program-strip">${programButtons()}</div>
 <div class="section-heading"><h2>${esc(p)}</h2><span>${esc(programPlain[p]||'')}${a?` · Bob’s advice: ${esc(adviceText[a]||a)}`:''} · ${esc(triedText(p))}</span></div>
 <div class="finding-gallery-heading"><span>Bob flagged ${report.findings.length} problems in this program</span><a href="#findings">See each one in the code ↗</a></div>
 <p class="assessment-label gallery-assessment">Each card says whether Bob was right, compared with our sealed answer list: ✓ right · ◐ partly right · ✗ wrong.</p>
 <div class="finding-gallery">${report.findings.map(f=>{const [vt,vc]=verdictFor(f);return `<article class="finding-card"><button class="finding-card-title" data-finding="${esc(f.id)}" aria-label="Open ${esc(problemNo(f))}"><span>${esc(plainFinding(f))}</span><b aria-hidden="true">↗</b></button><div class="finding-card-meta"><span>${esc(problemNo(f))} · ${esc(linesText(f))}</span><span class="verdict ${vc}">${esc(vt)}</span></div><div class="finding-card-top"><span class="rule-plain">${esc(ruleLabel(f.rule))}</span></div><details class="finding-code"><summary>Show the code <span aria-hidden="true">＋</span></summary><pre>${esc(f.evidence)}</pre></details></article>`;}).join('')}</div>
 <details class="study-method"><summary>How we judged Bob’s answers</summary><p>Before the hackathon we wrote down every hidden problem and sealed the list with a fingerprint (a hash) on 24 Sep, so nobody could change it after seeing Bob’s answers. “Right” here means right against that list. It does not mean the code was tested on a live SAP system.</p></details>`;
 bindPrograms($('overview-view'));$('overview-view').querySelectorAll('[data-finding]').forEach(b=>b.onclick=()=>{selected=b.dataset.finding;activeTab='source';location.hash='#findings';paintWorkspace();});
}
function paintWorkspace(){
 const page=['overview','findings','evidence'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
 document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $('overview-view').hidden=page!=='overview';$('atlas-view').hidden=page!=='evidence';
 ['findings','evidence','guide'].forEach(v=>$(v+'-view').classList.toggle('hidden',v!=='findings'||page!=='findings'));
 document.querySelector('.report-stats').classList.toggle('hidden',page!=='findings');
 $('page-title').textContent={overview:'Can IBM Bob review old SAP code?',findings:'See exactly what Bob found.',evidence:'What we did, and what we did not.'}[page];
 $('page-subtitle').textContent={overview:'We tested Bob like an exam, with the answers written down in advance. Here are the results.',findings:`Bob flagged ${report.findings.length} places in this program. Click a highlighted line to see the code, Bob’s reason, and whether Bob was right.`,evidence:'Each program went through four steps. A dashed box means the step is not done, so we make no claim about it.'}[page];
 const findingsArt=['overview','findings','evidence'].includes(page)&&window.CLEAN_CORE_DEMO_CONFIG?.SHOW_MASCOT===true;
 document.querySelector('.intro').classList.toggle('findings-hero',findingsArt);
 document.querySelector('.intro').classList.toggle('dossier-hero',page==='overview');
 document.querySelector('.hero-dossier').hidden=page!=='overview';
 const heroMascot=document.querySelector('.intro [data-mascot]');
 if(heroMascot){heroMascot.src=findingsArt?(page==='evidence'?'assets/bob-evidence-case.png':`assets/bob-${page}.png`):'assets/ibm-bob.webp';heroMascot.alt=findingsArt?{overview:'Bob holding the four program folders reviewed in this study',evidence:'Bob sorting completed, partial and missing evidence into an open case',findings:'Bob pointing to a flagged line in a code panel'}[page]:'IBM Bob';}
 $('breadcrumb-current').textContent=page;
 const recorded=!!recordedForCurrent();$('notice-label').textContent=recorded?'SAVED RESULTS':isDesign?'DESIGN EXAMPLE':'YOUR UPLOAD';$('notice-copy').textContent=recorded?'These are Bob’s answers from the hackathon runs, shown unchanged. Our judgements are kept separately.':isDesign?'Made-up findings that show how the page works. Bob did not produce them.':'Shown as found in your file. Nothing in it has been checked by us.';
 if(page==='overview')paintOverview();
 if(page==='findings')renderList();
 if(page==='evidence')paintAtlas();
}
// Keep existing import, filters, review and export handlers; repaint their new surroundings.
const oldNavigate=navigate;
navigate=function(view){oldNavigate(view);if(view==='evidence')location.hash='#evidence';paintWorkspace();};
window.addEventListener('hashchange',paintWorkspace);
async function loadRecordedAudits(){try{
 const response=await fetch('data/recorded-audits.json?v=confirmed-20260926');if(!response.ok)throw Error('Recorded reports unavailable');
 recordedAudits=await response.json();saveActiveReport();
 for(const item of recordedAudits){const r=validate(JSON.parse(item.raw));const key='recorded-'+r.program;if(!loadedReports.has(key))loadedReports.set(key,{report:r,rawText:item.raw,reviews:new Map(),missed:[],isDesign:false,selected:r.findings[0]?.id??null});}
 // Do not replace any report the user imported while the fixture was loading.
 if(activeReportKey==='design')switchReport('recorded-'+JSON.parse(recordedAudits[0].raw).program);
 renderReportPicker();paintWorkspace();
 }catch(e){notify(e.message);paintWorkspace();}}
function paintAtlas(){
 const heads=['Program','1 · Bob read it','2 · We checked Bob’s answers','3 · Bob rewrote it','4 · Tried on real SAP'];
 const of=v=>String(v).replace(' / ',' of ');
 $('atlas-view').innerHTML=`<div class="table-scroll"><table class="atlas-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${recordedAudits.map((x,i)=>{const r=JSON.parse(x.raw);return `<tr><th>${esc(r.program)}<small class="program-plain">${esc(programPlain[r.program]||'')}</small></th><td><div class="atlas-record">Done<small>Cost: ${x.coins.toFixed(3)} Bobcoin</small></div></td><td><div class="atlas-review">Rule problems: ${esc(of(x.core))}<small>Logic bugs: ${esc(of(x.bonus))}</small></div></td><td><div class="atlas-review">New code written<small>${i===0?'Fixed once after our review · 1.837 Bobcoin':'Part of one three-program run · not reviewed yet'}</small></div></td><td>${i===0?'<div class="atlas-review">Tried on a free SAP trial<small>Data view: did not start. Two SAP data sources Bob had marked “unconfirmed” do not exist on the trial.</small><small>Class: compiles. All 7 tests passed, using stand-in tables, so the logic is proven but not the SAP data link.</small></div>':'<div class="atlas-empty">Not done</div>'}</td></tr>`;}).join('')}</tbody></table></div>
 <p class="caption">For the last three programs, step 3 ran as one job: three Bob helpers worked side by side and wrote 13 files in 16 minutes for 1.76 Bobcoin. Nobody has reviewed or run those files yet. Tests that are written are not tests that passed.</p>
 <div class="atlas-panels"><section class="panel atlas-current"><div class="eyebrow">The report you are viewing</div><h2>${esc(programTitles[report.program]||'Your uploaded program')}</h2><code class="atlas-program-id">${esc(report.program)}</code><p>${esc(programPlain[report.program]||'This is the program named in your report')}. Bob flagged <strong>${report.findings.length} possible problems</strong> in its code.</p><label for="atlas-program-picker">Choose a different report</label><select id="atlas-program-picker" aria-describedby="atlas-selection-help">${[...loadedReports].filter(([k,v])=>k.startsWith('recorded-')||!v.isDesign||k===activeReportKey).map(([k,v])=>`<option value="${esc(k)}" ${k===activeReportKey?'selected':''}>${esc(programTitles[v.report.program]||v.report.program)}${k.startsWith('recorded-')?'':' · Your upload'}</option>`).join('')}</select><p class="caption" id="atlas-selection-help">This choice also sets the report shown on Overview and Findings. The table above always compares all four programs.</p><a href="#findings">Explore these ${report.findings.length} findings →</a></section><section class="panel"><div class="eyebrow">What remains for this program</div><h2>${report.program==='ZFI_VENDOR_AGING'&&recordedForCurrent()?'Real SAP data access still needs testing':'The new code still needs testing'}</h2><p>${report.program==='ZFI_VENDOR_AGING'&&recordedForCurrent()?'The original data view could not start on the SAP trial because two required SAP data sources are missing. The class compiled and its seven unit tests passed using stand-in tables. Those tests cover specific code behaviours; they do not verify access to real SAP data.':recordedForCurrent()?'Bob wrote a replacement for this program, but it has not yet been reviewed or run on SAP. Finding problems in the old code and proving the replacement works are separate steps.':'We have not checked this uploaded report or run its code on SAP. Any claims in the file still need supporting evidence.'}</p>${report.program==='ZFI_VENDOR_AGING'?'<a href="walkthrough.html">See this program’s before / after case →</a>':'<a href="walkthrough.html">See the separate supplier-invoice case →</a>'}</section></div>
 <p class="caption">Solid boxes: done and recorded. Dashed boxes: not done, so we make no claim. Trial record: docs/activation/README.md.</p>
 <section class="panel atlas-origin"><h2>About this report</h2><div id="atlas-origin-rows"></div></section>`;
 $('atlas-program-picker').onchange=e=>{switchReport(e.target.value);paintWorkspace();};
 renderEvidence();$('atlas-origin-rows').innerHTML=$('evidence-rows').innerHTML;
}
renderEvidence=function(){const recorded=!!recordedForCurrent();const rows=[['Program',report.program+(programPlain[report.program]?' · '+programPlain[report.program]:'')],['Code file',report.source_file],['Who wrote the findings',recorded?'IBM Bob, in our “Clean Core Architect” mode':isDesign?'Nobody: a made-up example':'Taken from your uploaded file'],['Rule list Bob used',report.provenance.catalogue_version],['Checked by people?',recorded?'Yes. Claude scored it and Sena confirmed it on 26 Sep':'Not by us'],['Tried on a real SAP system?',report.program==='ZFI_VENDOR_AGING'&&recorded?'Partly, on a free trial system: 7 tests passed with stand-in tables (see step 4 above)':'No'],['Bob’s original answer','Kept unchanged. Our judgements are stored separately']];$('evidence-rows').innerHTML=rows.map(([a,b])=>`<div class="evidence-row"><span>${esc(a)}</span><span>${esc(b)}</span></div>`).join('');};
const dossierPrograms=document.createElement('aside');dossierPrograms.className='dossier-programs';document.querySelector('.review-grid').prepend(dossierPrograms);
let wrapSource=false;
const sourcePanel=document.querySelector('[aria-label="Findings list"]');
sourcePanel.classList.add('source-panel');
const codeTools=document.createElement('div');codeTools.className='code-tools';
codeTools.innerHTML='<span>ABAP <small>Original source</small></span><div><button type="button" id="jump-source">Go to selected line ↓</button><button type="button" id="wrap-source" aria-pressed="false">Wrap lines</button><button type="button" id="expand-source" aria-pressed="false">Expand code ↗</button></div>';
sourcePanel.querySelector('.list-heading').after(codeTools);
$('wrap-source').onclick=()=>{wrapSource=!wrapSource;sourcePanel.classList.toggle('wrap-source',wrapSource);$('wrap-source').setAttribute('aria-pressed',String(wrapSource));};
$('expand-source').onclick=()=>{const expanded=document.querySelector('.review-grid').classList.toggle('code-expanded');$('expand-source').setAttribute('aria-pressed',String(expanded));$('expand-source').textContent=expanded?'Restore layout ↙':'Expand code ↗';};
$('jump-source').onclick=()=>{const line=$('finding-list').querySelector('.selected-line');if(line)line.scrollIntoView({block:'center',behavior:'instant'});};
let renderedSourceProgram=null;
renderList=function(){
 const oldDocument=$('finding-list').querySelector('.source-document');
 const oldPosition=renderedSourceProgram===report.program&&oldDocument?{top:oldDocument.scrollTop,left:oldDocument.scrollLeft}:null;
 renderedSourceProgram=report.program;
 dossierPrograms.innerHTML=programButtons()+`<p class="caption">Across all four programs Bob caught 27 of 29 rule problems and 1 of 12 logic bugs.</p>`;bindPrograms(dossierPrograms);
 const query=$('search').value.toLowerCase(),status=$('filter').value;
 const findings=report.findings.filter(f=>(status==='all'||f.verification_status===status)&&[f.id,f.rule,f.reason,f.evidence].join(' ').toLowerCase().includes(query));
 const current=recordedForCurrent();document.querySelector('.list-heading').textContent='The program’s code · '+report.source_file;
 $('finding-list').innerHTML=current?`<div class="source-document">${current.source.split('\n').map((line,i)=>{const matches=findings.filter(f=>i+1>=f.line_start&&i+1<=f.line_end);const start=matches.filter(f=>f.line_start===i+1);const level=matches.some(f=>f.level_hint==='D')?'level-d':matches.some(f=>f.level_hint==='C')?'level-c':'level-other';return `<div class="source-row ${matches.length?level:''} ${matches.some(f=>f.id===selected)?'selected-line':''}"><span class="source-number">${i+1}</span><code>${esc(line)||' '}</code><span>${start.map(f=>`<button class="source-pill" data-id="${esc(f.id)}" title="${esc(ruleLabel(f.rule))}">${esc(problemNo(f))} ${esc(verdictFor(f)[0].slice(0,1))}</button>`).join('')}</span></div>`;}).join('')}</div><p class="caption source-legend">Highlighted lines are the places Bob flagged. Red: Bob rates it the riskiest kind, such as writing straight into SAP tables. Green: it uses SAP internals that need a supported replacement. Click a label to open that problem.</p>`:findings.map(f=>`<button class="finding ${f.id===selected?'selected':''}" data-id="${esc(f.id)}"><strong>${esc(plainFinding(f))}</strong><p>${esc(problemNo(f))} · ${esc(ruleLabel(f.rule))}</p><span>${esc(linesText(f))}</span></button>`).join('');
 $('list-count').textContent=`${findings.length} problems shown`;
 const newDocument=$('finding-list').querySelector('.source-document');if(oldPosition&&newDocument){newDocument.scrollTop=oldPosition.top;newDocument.scrollLeft=oldPosition.left;}
 $('finding-list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();});renderDetail();
};
renderDetail=function(){const f=report.findings.find(x=>x.id===selected);if(!f){$('detail').innerHTML='<p class="empty">Click a highlighted line to see a problem.</p>';return;}
 const [vt,vc,vx]=verdictFor(f);const recorded=!!recordedForCurrent();
 $('detail').innerHTML=`<div class="detail-head">${recorded?`<span class="verdict big ${vc}">${esc(vt)}</span>`:''}<h2>${esc(plainFinding(f))}</h2><span class="rule">${esc(problemNo(f))} · ${esc(linesText(f))}</span><p class="caption">${esc(ruleLabel(f.rule))} · ${esc(statusText[f.verification_status])}</p></div><div class="detail-body"><h3 class="subhead">The code Bob pointed at</h3><pre class="code-dark">${esc(f.evidence)}</pre><h3 class="subhead">Why Bob flagged it, in Bob’s words</h3><p class="body-copy">${esc(f.reason)}</p><h3 class="subhead">What Bob suggests instead</h3><p class="caption">A suggestion only. It has not been run on SAP.</p><pre class="code-dark">${esc(f.suggested_action)}</pre><h3 class="subhead">What Bob said it could not know</h3><ul class="unknown-list">${f.unknowns.length?f.unknowns.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>Bob listed nothing here.</li>'}</ul>${recorded?`<section class="assessment-box"><h3 class="subhead">Was Bob right?</h3><p>${esc(vx)}</p><small>Checked by Claude against the sealed answer list, confirmed by Sena on 26 Sep.</small></section>`:''}<label for="review-decision" class="subhead">Your own verdict (optional)</label><select id="review-decision" class="review-select" aria-label="Your verdict"><option value="not_reviewed">Not decided</option><option value="correct">Bob was right</option><option value="incorrect">Bob was wrong</option><option value="partially_correct">Partly right</option></select><p class="caption">Your choice stays in this browser. It never changes Bob’s original answer.</p></div>`;
 if(f.source_url){try{const u=new URL(f.source_url);if(['https:','http:'].includes(u.protocol)){const a=document.createElement('a');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open the source Bob cited ↗';a.className='small-link';$('detail').querySelector('.detail-body').append(a);}}catch{}}
 $('review-decision').value=reviewOf(f);$('review-decision').onchange=e=>{reviews.set(f.id,e.target.value);renderStats();notify('Your verdict is saved in this browser tab. Use Export to keep it.');};
};

document.querySelectorAll('[data-mascot]').forEach(img=>{if(window.CLEAN_CORE_DEMO_CONFIG?.SHOW_MASCOT===true){img.src=img.dataset.mascotSrc||'assets/ibm-bob.webp';img.hidden=false;img.closest('.mascot-slot')?.classList.add('has-mascot');}});
// Retain review work across the site's two HTML documents in this tab only.
try{const saved=JSON.parse(sessionStorage.getItem('ccc-workspace-v1')||'null');if(saved){
 const restored=saved.entries.map(([key,state])=>{validate(state.report);if(JSON.stringify(JSON.parse(state.rawText))!==JSON.stringify(state.report))throw Error('Saved raw report mismatch');if(!Array.isArray(state.reviews)||!Array.isArray(state.missed)||!state.missed.every(x=>typeof x==='string'))throw Error('Invalid saved review');for(const [id,v] of state.reviews)if(!state.report.findings.some(f=>f.id===id)||!['not_reviewed','correct','incorrect','partially_correct'].includes(v))throw Error('Invalid saved decision');return [key,{...state,reviews:new Map(state.reviews)}];});
 for(const [key,state] of restored)loadedReports.set(key,state);reportSequence=saved.sequence||0;if(loadedReports.has(saved.active)){activeReportKey=saved.active;({report,rawText,reviews,missed,isDesign,selected}=loadedReports.get(saved.active));renderStats();renderMissed();renderReportPicker();}
}}catch{notify('Saved workspace could not be restored. Import an exported review bundle to recover it.');}
window.addEventListener('pagehide',()=>{try{saveActiveReport();sessionStorage.setItem('ccc-workspace-v1',JSON.stringify({active:activeReportKey,sequence:reportSequence,entries:[...loadedReports].map(([k,s])=>[k,{...s,reviews:[...s.reviews]}])}));}catch{/* Exports remain the durable save path when browser storage is unavailable. */}});
$('search').addEventListener('input',()=>renderList());$('filter').addEventListener('change',()=>renderList());
const originalPicker=renderReportPicker;renderReportPicker=function(){originalPicker();paintWorkspace();};
paintWorkspace();loadRecordedAudits();
