// Presentation and separately labelled assessment; never modifies Bob's raw JSON.
let recordedAudits=[];
const assessmentLabel='Scored by Claude - confirmed by Sena, 26 Sep';
function recordedForCurrent(){return recordedAudits.find(x=>x.raw===rawText);}
const findingHeadlines={"ZFI_VENDOR_AGING": ["Reads accounting tables whose cloud availability needs checking.", "Reads supplier data directly from an SAP table.", "Uses native SQL, which ABAP Cloud does not allow.", "Uses an old-style table with an implicit header row.", "Writes a file to the application server instead of a cloud integration.", "Starts another classic report with SUBMIT.", "Claims to convert currency, but only updates a log.", "Bob flags the report structure correctly, but uses the wrong rule."], "ZSD_OPEN_ORDERS": ["Declares a work area tied to classic SAP GUI screens.", "Uses an old-style table with an implicit header row.", "Bob questions a type reference to a database field.", "Bob questions another type reference to a database field.", "Uses a classic selection screen and a database-field type.", "Reads sales headers directly from an SAP table.", "Runs database queries inside nested loops.", "Reads sales items directly from an SAP table.", "Reads delivery status directly from an SAP table.", "Reads customer data directly from an SAP table.", "Bob questions MOVE-CORRESPONDING; the assessment disagrees.", "Uses a classic subroutine instead of a method.", "Uses another classic subroutine instead of a method.", "Calls the classic subroutines flagged above.", "Prints a classic list that needs a cloud UI replacement.", "Uses a control break in the classic list output.", "Uses an older arithmetic statement.", "The delivery-status comment does not match its filter."], "ZMM_MASS_PRICE_UPDATE": ["Calls a GUI popup that is unavailable in ABAP Cloud.", "Reads material prices directly from an SAP table.", "Updates SAP prices directly, bypassing standard posting logic.", "Replays SAP GUI screens to change a material.", "Prints a classic list that needs a cloud UI replacement.", "Uses classic subroutines instead of methods.", "Bob questions declarations; the assessment disagrees.", "Changes standard prices without checking price control."], "ZCC_LEGACY_MATERIALS": ["Declares a work area tied to classic SAP GUI screens.", "Uses a selection screen that depends on SAP GUI.", "Reads material data directly from an SAP table.", "Prints a classic list that needs a cloud UI replacement.", "Displays a grid through a classic SAP GUI function.", "Prints another classic list line; this repeats an earlier issue."]};
function plainFinding(f){const a=recordedForCurrent();const n=Number(f.id.replace("F-",""))-1;return a&&findingHeadlines[report.program]?.[n]||f.title||f.reason.split(/\n|\. /)[0];}
function assessmentFor(f){
 const value=recordedForCurrent()?.assessment[f.id]||'';
 if(/^(Match|Bonus) /.test(value))return 'Answer key: agrees';
 if(value.startsWith('Duplicate '))return 'Answer key: agrees · repeated issue';
 if(['Partially correct','Incorrect','Correct extra','Correct observation - unscored'].includes(value))return value;
 return 'Undecided';
}
function programButtons(){
 const button=([key,s])=>`<button class="program-card ${key===activeReportKey?'chosen':''}" data-program="${esc(key)}"><strong>${esc(s.report.program)}</strong><span>${s.report.findings.length} findings · ${key.startsWith('recorded-')?'Recorded report':s.isDesign?'Design example':'Your import'}</span></button>`;
 const entries=[...loadedReports];const main=entries.filter(([key])=>key.startsWith('recorded-'));
 const imports=entries.filter(([key,s])=>!key.startsWith('recorded-')&&!s.isDesign);
 return main.map(button).join('')+(imports.length?`<details class="your-imports" ${imports.some(([key])=>key===activeReportKey)?'open':''}><summary>Your imports (${imports.length})</summary><div class="program-strip">${imports.map(button).join('')}</div></details>`:'');
}
function bindPrograms(node){node.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>{const page=location.hash;switchReport(b.dataset.program);location.hash=page||'#overview';paintWorkspace();});}
function paintOverview(){
 const cards=[['Core issues found','27 / 29','Includes one non-catalogue runtime issue'],['Bonus issues found','1 / 12','Planted issues outside the core set'],['Duplicates','6 / 40','Raw findings retained in every report'],['Precision','29 / 32','over decided findings; 6 duplicates and 2 unscored observations excluded'],['Bobcoin used','≈2.5 / 40','2.498 total · four audits + tasks 5–6']];
 $('overview-view').innerHTML=`<p class="assessment-label">Recorded study · four synthetic programs · ${assessmentLabel}</p><div class="metric-grid">${cards.map(([t,v,n])=>t==='Bobcoin used'?`<article class="metric metric-coins">${window.CLEAN_CORE_DEMO_CONFIG?.SHOW_MASCOT===true?'<img class="coin-art" src="assets/bob-coins.png" alt="" width="200" height="200">':''}<div class="coin-summary"><span class="eyebrow">Bobcoin used</span><div class="coin-value"><strong>${v}</strong><span>Bobcoin</span></div><p>Four audits + modernization + review fixes</p><div class="coin-budget"><div class="coin-track" role="meter" aria-label="Recorded Bobcoin usage" aria-valuemin="0" aria-valuemax="40" aria-valuenow="2.498"><span style="width:6.245%"></span></div><div class="coin-budget-labels"><span>2.498 / 40 Bobcoin</span><span>6.245% used</span></div></div><small>${assessmentLabel} · recorded snapshot</small></div></article>`:`<article class="metric"><span>${t}</span><strong>${v}</strong><small>${n}</small><small>${assessmentLabel}</small></article>`).join('')}</div><details class="study-method"><summary>Study scope & cost sources</summary><p>Scores are sample-author-key comparisons, not independent validation or a general accuracy benchmark. Source: docs/scoring/zcc_legacy_materials.md; task costs from the six recorded task summaries.</p></details><div class="program-strip">${programButtons()}</div><div class="section-heading"><h2>${esc(report.program)}</h2><span>Needs target verification · Bob draft: ${esc(report.summary.draft_verdict_hint||'Not supplied')}</span></div><div class="finding-gallery-heading"><span>${report.findings.length} recorded findings</span><a href="#findings">Open review workspace ↗</a></div><p class="assessment-label gallery-assessment">Answer-key labels: ${assessmentLabel}</p><div class="finding-gallery">${report.findings.map(f=>`<article class="finding-card"><button class="finding-card-title" data-finding="${esc(f.id)}" aria-label="Review ${esc(f.id)}"><span>${esc(plainFinding(f))}</span><b aria-hidden="true">↗</b></button><div class="finding-card-meta"><span>${esc(f.id)} · ${esc(f.rule)} · lines ${f.line_start}–${f.line_end}</span><span class="key-match">${esc(assessmentFor(f))}</span></div><div class="finding-card-top"><span class="pill">${esc(statusText[f.verification_status])}</span></div><details class="finding-code"><summary>View code evidence <span aria-hidden="true">＋</span></summary><pre>${esc(f.evidence)}</pre></details></article>`).join('')}</div><details class="study-method"><summary>How these findings were assessed</summary><p>Scored against an answer key frozen 24 Sep for synthetic samples. Assessment is separate from Bob’s raw output, was confirmed by Sena on 26 Sep, and does not establish target-system verification.</p></details>`;
 bindPrograms($('overview-view'));$('overview-view').querySelectorAll('[data-finding]').forEach(b=>b.onclick=()=>{selected=b.dataset.finding;activeTab='source';location.hash='#findings';paintWorkspace();});
}
function paintWorkspace(){
 const page=['overview','findings','evidence'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
 document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $('overview-view').hidden=page!=='overview';$('atlas-view').hidden=page!=='evidence';
 ['findings','evidence','guide'].forEach(v=>$(v+'-view').classList.toggle('hidden',v!=='findings'||page!=='findings'));
 document.querySelector('.report-stats').classList.toggle('hidden',page!=='findings');
 $('page-title').textContent={overview:'Legacy ABAP, audited.',findings:'Inspect the evidence.',evidence:'What was done, and what was not.'}[page];
 $('page-subtitle').textContent={overview:'Four legacy programs, one rule catalogue, a frozen answer key. Numbers first.',findings:`Bob read this program and flagged ${report.findings.length} places. Click one to see the line, Bob’s reason, and whether the answer key agrees.`,evidence:'What was done and what was not. Empty cells are claims we did not make.'}[page];
 $('breadcrumb-current').textContent=page;
 if(page==='overview')paintOverview();
 if(page==='findings')renderList();
 if(page==='evidence')paintAtlas();
}
// Keep existing import, filters, review and export handlers; repaint their new surroundings.
const oldNavigate=navigate;
navigate=function(view){oldNavigate(view);if(view==='evidence')location.hash='#evidence';paintWorkspace();};
window.addEventListener('hashchange',paintWorkspace);
async function loadRecordedAudits(){try{
 const response=await fetch('data/recorded-audits.json?v=confirmed-20260926');if(!response.ok)throw Error('Recorded reports unavailable');
 recordedAudits=await response.json();saveActiveReport();
 for(const item of recordedAudits){const r=validate(JSON.parse(item.raw));const key='recorded-'+r.program;if(!loadedReports.has(key))loadedReports.set(key,{report:r,rawText:item.raw,reviews:new Map(),missed:[],isDesign:false,selected:r.findings[0]?.id??null});}
 // Do not replace any report the user imported while the fixture was loading.
 if(activeReportKey==='design')switchReport('recorded-'+JSON.parse(recordedAudits[0].raw).program);
 renderReportPicker();paintWorkspace();
 }catch(e){notify(e.message);paintWorkspace();}}
function paintAtlas(){
 $('atlas-view').innerHTML=`<p class="assessment-label">Recorded study snapshot · ${assessmentLabel}</p><div class="table-scroll"><table class="atlas-table"><thead><tr><th>Program</th><th>01 / Audit</th><th>02 / Scored against key</th><th>03 / Modernized</th><th>04 / Verified on target</th></tr></thead><tbody>${recordedAudits.map((x,i)=>{const r=JSON.parse(x.raw);return `<tr><th>${esc(r.program)}</th><td><div class="atlas-record">Recorded report<small>${x.coins.toFixed(3)} Bobcoin</small></div></td><td><div class="atlas-review">Core ${x.core}<small>Bonus ${x.bonus} · confirmed assessment</small></div></td><td><div class="atlas-review">${i===0?'Candidate files':'Candidate files · review open'}<small>${i===0?'Tasks 5–6 · 1.837 Bobcoin · trial attempt recorded':'Task 7 · parallel run · not activated'}</small></div></td><td>${i===0?'<div class="atlas-review">Attempted on trial<small>CDS: 2 errors · class: recheck pending</small><small>Earlier ATC: 0 · full-source rerun pending</small><small>Source: docs/activation/README.md</small></div>':'<div class="atlas-empty">Not performed</div>'}</td></tr>`;}).join('')}</tbody></table></div><p class="caption">Task 7: three parallel sub-agents produced 13 files in 16 minutes, using 1.76 Bobcoin for the whole run. Sources: modernized/PARALLEL_RUN.md · docs/scoring/parallel_modernization.md. Candidate files are awaiting review and target checks; written tests are not executed tests.</p><div class="atlas-panels"><section class="panel"><div class="eyebrow">Selected program</div><h2>${esc(report.program)}</h2><p>Needs target verification</p><a href="#findings">Open recorded findings →</a></section><section class="panel"><div class="eyebrow">Next evidence needed</div><h2>Activation · ATC · ABAP Unit</h2><p>ZFI trial attempt recorded: CDS blocked by two missing data sources; earlier class activation and ATC 0 were recorded, but the remote class was subsequently found to be an empty shell. Full-source activation, ATC and ABAP Unit must be rerun. Customer-target verification is still needed.</p><a href="walkthrough.html">Inspect the case or attach records →</a></section></div><p class="caption">Trial results: docs/activation/README.md (26 Sep). Earlier class/ATC results do not validate the full rewrite: remote source completeness was not established. The test include and main class have now been repasted; rerun pending. ATC 0 does not validate the inactive CDS. Solid cells: recorded artifacts or confirmed assessments. Dashed cells: no performed step in this snapshot. Case imports are local and do not update this study table automatically.</p><section class="panel atlas-origin"><h2>Selected report origin</h2><div id="atlas-origin-rows"></div></section>`;
 renderEvidence();$('atlas-origin-rows').innerHTML=$('evidence-rows').innerHTML;
}
const dossierPrograms=document.createElement('aside');dossierPrograms.className='dossier-programs';document.querySelector('.review-grid').prepend(dossierPrograms);
renderList=function(){
 dossierPrograms.innerHTML=programButtons()+`<p class="assessment-label">${assessmentLabel}</p><p class="caption">Four recorded audits: core 27 / 29 · bonus 1 / 12. Snapshot, not scores for arbitrary imports.</p>`;bindPrograms(dossierPrograms);
 const query=$('search').value.toLowerCase(),status=$('filter').value;
 const findings=report.findings.filter(f=>(status==='all'||f.verification_status===status)&&[f.id,f.rule,f.reason,f.evidence].join(' ').toLowerCase().includes(query));
 const current=recordedForCurrent();document.querySelector('.list-heading').textContent=report.source_file;
 $('finding-list').innerHTML=current?`<div class="source-document">${current.source.split('\n').map((line,i)=>{const matches=findings.filter(f=>i+1>=f.line_start&&i+1<=f.line_end);const start=matches.filter(f=>f.line_start===i+1);const level=matches.some(f=>f.level_hint==='D')?'level-d':matches.some(f=>f.level_hint==='C')?'level-c':'level-other';return `<div class="source-row ${matches.length?level:''} ${matches.some(f=>f.id===selected)?'selected-line':''}"><span class="source-number">${i+1}</span><code>${esc(line)||' '}</code><span>${start.map(f=>`<button class="source-pill" data-id="${esc(f.id)}">${esc(f.id)} · ${esc(f.rule)} · ${esc(f.level_hint||'Unclassified')}</button>`).join('')}</span></div>`;}).join('')}</div><p class="caption source-legend">Bob level hints: D · red, C · green, other · neutral. Colour is a reported classification, not target verification.</p>`:findings.map(f=>`<button class="finding ${f.id===selected?'selected':''}" data-id="${esc(f.id)}"><strong>${esc(plainFinding(f))}</strong><p>${esc(f.id)} · ${esc(f.rule)}</p><span>L${f.line_start}–${f.line_end} · ${esc(statusText[f.verification_status])}</span></button>`).join('');
 $('list-count').textContent=`${findings.length} findings match the filter`;
 $('finding-list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();});renderDetail();
};
renderDetail=function(){const f=report.findings.find(x=>x.id===selected);if(!f){$('detail').innerHTML='<p class="empty">Select a finding to inspect.</p>';return;}
 $('detail').innerHTML=`<div class="detail-head"><h2>${esc(plainFinding(f))}</h2><span class="rule">${esc(f.id)} · ${esc(f.rule)} · ${esc(f.level_hint||'Unclassified')}</span><p class="caption">Lines ${f.line_start}–${f.line_end}</p><span class="pill">${esc(statusText[f.verification_status])}</span></div><div class="detail-body"><h3 class="subhead">Bob’s reason</h3><p class="body-copy">${esc(f.reason)}</p><h3 class="subhead">Reported evidence</h3><pre class="code-dark">${esc(f.evidence)}</pre><h3 class="subhead">Suggested action · candidate</h3><pre class="code-dark">${esc(f.suggested_action)}</pre><h3 class="subhead">Unknowns Bob left open</h3><ul class="unknown-list">${f.unknowns.length?f.unknowns.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>No unknowns recorded; completeness not established.</li>'}</ul><section class="assessment-box"><h3 class="subhead">Answer-key assessment</h3><p>${esc(assessmentFor(f))}</p><small>${assessmentLabel}</small></section><label for="review-decision" class="subhead">Your review decision</label><select id="review-decision" class="review-select" aria-label="Assessment"><option value="not_reviewed">Undecided / not reviewed</option><option value="correct">Correct</option><option value="incorrect">Wrong</option><option value="partially_correct">Partially correct</option></select><p class="caption">Review decisions export separately from Bob’s raw JSON. A review does not mark code as verified on SAP.</p></div>`;
 if(f.source_url){try{const u=new URL(f.source_url);if(['https:','http:'].includes(u.protocol)){const a=document.createElement('a');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open Bob’s cited reference ↗';a.className='small-link';$('detail').querySelector('.detail-body').append(a);}}catch{}}
 $('review-decision').value=reviewOf(f);$('review-decision').onchange=e=>{reviews.set(f.id,e.target.value);renderStats();notify('Review stored in this session. Export review to save.');};
};

document.querySelectorAll('[data-mascot]').forEach(img=>{if(window.CLEAN_CORE_DEMO_CONFIG?.SHOW_MASCOT===true){img.src='assets/ibm-bob.webp';img.hidden=false;img.closest('.mascot-slot')?.classList.add('has-mascot');}});
// Retain review work across the site's two HTML documents in this tab only.
try{const saved=JSON.parse(sessionStorage.getItem('ccc-workspace-v1')||'null');if(saved){
 const restored=saved.entries.map(([key,state])=>{validate(state.report);if(JSON.stringify(JSON.parse(state.rawText))!==JSON.stringify(state.report))throw Error('Saved raw report mismatch');if(!Array.isArray(state.reviews)||!Array.isArray(state.missed)||!state.missed.every(x=>typeof x==='string'))throw Error('Invalid saved review');for(const [id,v] of state.reviews)if(!state.report.findings.some(f=>f.id===id)||!['not_reviewed','correct','incorrect','partially_correct'].includes(v))throw Error('Invalid saved decision');return [key,{...state,reviews:new Map(state.reviews)}];});
 for(const [key,state] of restored)loadedReports.set(key,state);reportSequence=saved.sequence||0;if(loadedReports.has(saved.active)){activeReportKey=saved.active;({report,rawText,reviews,missed,isDesign,selected}=loadedReports.get(saved.active));renderStats();renderMissed();renderReportPicker();}
}}catch{notify('Saved workspace could not be restored. Import an exported review bundle to recover it.');}
window.addEventListener('pagehide',()=>{try{saveActiveReport();sessionStorage.setItem('ccc-workspace-v1',JSON.stringify({active:activeReportKey,sequence:reportSequence,entries:[...loadedReports].map(([k,s])=>[k,{...s,reviews:[...s.reviews]}])}));}catch{/* Exports remain the durable save path when browser storage is unavailable. */}});
$('search').addEventListener('input',()=>renderList());$('filter').addEventListener('change',()=>renderList());
const originalPicker=renderReportPicker;renderReportPicker=function(){originalPicker();paintWorkspace();};
paintWorkspace();loadRecordedAudits();
